name: "Daniel Spector"
pygments: true
permalink: :title
exclude: [README.md, LICENSE, Makefile]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# Information for the Atom feed
danielspector:
   author: "Daniel Spector"
   email: "danielyspector@gmail.com"
